"""add missing profile columns

Revision ID: 1d615d44635a
Revises: 
Create Date: 2026-06-08 16:00:12.280108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d615d44635a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.add_column('execution_plans', sa.Column('roadmap_json', sa.JSON(), nullable=True))
    op.add_column('goal_context', sa.Column('context_json', sa.JSON(), nullable=True))
    op.add_column('goals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('persona', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('motivation_style', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('risk_profile', sa.String(length=50), nullable=True))
    op.alter_column('profiles', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('progress_logs', sa.Column('completion_percent', sa.Integer(), nullable=True))
    op.add_column('progress_logs', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('readiness_analyses', sa.Column('analysis_json', sa.JSON(), nullable=True))
    op.add_column('reflections', sa.Column('reflection_text', sa.Text(), nullable=True))
    op.add_column('replanning_history', sa.Column('old_plan', sa.JSON(), nullable=True))
    op.add_column('replanning_history', sa.Column('new_plan', sa.JSON(), nullable=True))
    op.add_column('replanning_history', sa.Column('reason', sa.Text(), nullable=True))
    op.alter_column('replanning_history', 'replanning_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('replanning_history', 'new_hours_per_week',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    op.alter_column('replanning_history', 'risk_analysis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('replanning_history', 'recommended_adjustments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('strategies', sa.Column('strategy_json', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('estimated_hours', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'estimated_hours')
    op.drop_column('tasks', 'title')
    op.drop_column('strategies', 'strategy_json')
    op.alter_column('replanning_history', 'recommended_adjustments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('replanning_history', 'risk_analysis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('replanning_history', 'new_hours_per_week',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('replanning_history', 'replanning_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('replanning_history', 'reason')
    op.drop_column('replanning_history', 'new_plan')
    op.drop_column('replanning_history', 'old_plan')
    op.drop_column('reflections', 'reflection_text')
    op.drop_column('readiness_analyses', 'analysis_json')
    op.drop_column('progress_logs', 'notes')
    op.drop_column('progress_logs', 'completion_percent')
    op.alter_column('profiles', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('profiles', 'risk_profile')
    op.drop_column('profiles', 'motivation_style')
    op.drop_column('profiles', 'persona')
    op.drop_column('goals', 'description')
    op.drop_column('goal_context', 'context_json')
    op.drop_column('execution_plans', 'roadmap_json')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    # ### end Alembic commands ###
