from typing import TypedDict, List, Dict, Any, Optional

class GoalState(TypedDict):
    # Core identification
    user_id: str
    goal_id: str
    
    # 1. Goal Intake & Discovery
    goal_title: str
    profile: Dict[str, Any]                 # User's onboarding profile metadata
    goal_context: Optional[Dict[str, Any]]     # Category, difficulty, estimated_duration, required_skills, risks, qa_context
    
    # 2. Strategy Option Phase
    strategies: List[Dict[str, Any]]        # 3 options generated by Gemini
    selected_strategy_key: Optional[str]    # Key selected by user (Checkpoint 1)
    
    # 3. Readiness check
    readiness: Optional[Dict[str, Any]]      # Scores, dimension_scores, gaps, steps
    
    # 4. Blueprint phase
    execution_plan: Optional[Dict[str, Any]] # Total phases, refinement choice (Checkpoint 2)
    tasks: List[Dict[str, Any]]              # Complete checklist with aliases and estimation durations
    dependencies: List[Dict[str, Any]]       # Array of dependency mappings: {"task_id_alias": "", "depends_on_alias": ""}
    
    # 5. Scheduling phase
    active_schedule: Optional[Dict[str, Any]] # Weekly hour budgets, daily time blocks calendar
    
    # 6. Execution & Feedback
    progress: Dict[str, Any]                 # Streaks, completion rate, completed list
    reflections: List[Dict[str, Any]]        # journal records, history
    coach_insights: Optional[Dict[str, Any]] # daily recommendations, warning risk levels
    
    # 7. Adaptive Replanning (Checkpoint 3)
    replanning_history: List[Dict[str, Any]]
    replanned_preview: Optional[Dict[str, Any]]
